export type RootStackParamList = {
  Splash: undefined
  OnBoarding: undefined
  Login: undefined
  LoginMail: undefined
  Otp: undefined
  Registration: undefined
  DocumentVerify: undefined
  VehicleRegistration: undefined
  BankDetail: undefined
  TabNav: undefined
  CreateAccount: undefined
  Settings: undefined
  AppSettings: undefined
  MyWallet: undefined
  TopupWallet: undefined
  Chat: undefined
  AddNewOffer: undefined
  OfferList: undefined
  ProfileSetting: undefined
  EndRide: undefined
  RentalDetails: undefined
  DocumentDetail: undefined
  BankDetails: undefined
  VehicleDetail: undefined
  Notification: undefined
  Subscription: undefined
  Map: undefined
  AddVehicle: undefined
  VehicleList: undefined
  ResetPassword: undefined
  OtpVerify: undefined
  SupportTicket: undefined
  CreateTicket: undefined
  TicketDetails: undefined
  PaymentSelect: undefined
  PaymentWebView: undefined
  AcceptFare: undefined
  ActiveRide: undefined
  Home: undefined
  OtpRide: undefined
  Ride: undefined
  RideComplete: undefined
  RideDetails: undefined
  MyRide: undefined
  CompleteRide: undefined
  CancelRide: undefined
  PendingRide: undefined
  PendingDetails: undefined
  CompleteDetails: undefined
  CancelDetails: undefined
  MapDetails: undefined
  NoService: undefined
  UploadedDocument: undefined
  FleetDetails: undefined
  RideInfo: undefined
  Verification: undefined
  AmbulanceTrack: undefined
  DriverList: undefined
  ManageVehicle: undefined
  TopUp: undefined
  TotalEarnings: undefined
  DashBoard: undefined
  MapWebView: undefined
  PdfViewer: undefined
}
