type AppColors = {
  white: string
  black: string
  primary: string
  subPrimary: string
  primaryFont: string
  secondaryFont: string
  graybackground: string
  bordercolor: string
  red: string
  border: string
  delBackground: string
  primaryLight: string
  greenborder: string
  cardicon: string
  price: string
  subFont: string
  modelBg: string
  alertBg: string
  alertIconBg: string
  alertBorder: string
  invoiceBtn: string
  darkThemeSub: string
  categoryTitle: string
  alertRed: string
  activeColor: string
  completeColor: string
  scheduleColor: string
  darkborder: string
  closeBg: string
  darkPurpal: string
  lightPurpal: string
  lightRed: string
  primaryBg: string
  subCategorytag: string
  darkBorderBlack: string
  dotPrimary: string
  bgDark: string
  darkFillBar: string
  darkText: string
  planNote: string
  dropDownColor: string
  planDot: string
  planLine: string
  round: string
  grayRound: string
  tagColor: string
  loader: string
  pink: string
  lightPink: string
  lightOrange: string
  lightGreen: string
  lightYellow: string
  railFillBackgroundColor: string
  loaderBackground: string
  loaderLightHighlight: string
  iconColor: string
  line: string
  darkLine: string
}

const appColors: AppColors = {
  loaderBackground: '#E8E8E8',
  loaderLightHighlight: '#F2F8FC',
  white: '#fff',
  black: '#000',
  darkText: '#BCBCBC',
  primary: '#199675',
  darkFillBar: '#303E3A',
  dotPrimary: '#2F4841',
  lightYellow: '#FFF7E5',
  pink: '#ff00ff',
  lightPink: '#F2E5FF',
  subPrimary: '#C9E2DB',
  lightGreen: '#ECF4FB',
  primaryFont: '#1F1F1F',
  secondaryFont: '#8F8F8F',
  graybackground: '#F5F5F5',
  border: '#E9E9E9',
  delBackground: '#FFEDED',
  primaryLight: '#32A284',
  greenborder: '#8ECCBB',
  cardicon: '#E8F4F1',
  price: '#20B149',
  red: '#FF4B4B',
  alertRed: '#F33737',
  subFont: '#171C26',
  modelBg: 'rgba(0, 0, 0, 0.5)',
  railFillBackgroundColor: 'rgba(223, 236,233, 0.5)',
  bordercolor: '#E9E9E9',
  alertBg: '#F6E4E4',
  alertIconBg: '#F7D5D5',
  alertBorder: '#F8C5C5',
  invoiceBtn: '#E0E0E0',
  darkThemeSub: '#343434',
  categoryTitle: '#8CCBBA',
  activeColor: '#3F8FDA',
  completeColor: '#FFB400',
  scheduleColor: '#7F00FF',
  darkborder: '#474747',
  closeBg: '#CFCDC6',
  darkPurpal: '#C084FC',
  lightPurpal: '#F9F3FF',
  lightRed: '#FFEDED',
  primaryBg: '#DFECE9',
  subCategorytag: '#F0EAF6',
  darkBorderBlack: '#797D83',
  bgDark: '#272727',
  planNote: '#F5F6F7',
  dropDownColor: '#fafafa',
  planDot: '#47AB91',
  planLine: '#9DCFC2',
  round: '#1B8569',
  grayRound: '#D0D3D8',
  tagColor: '#E8F5F2',
  loader: '#EEEEEE',
  lightOrange: '#FEEBEB',
  iconColor: '#777777',
  line: '#C7CACF',
  darkLine: '#1A8065'
}
export default appColors
