export const editProfile = 'updateProfile'
export const changePassword = 'updatePassword'
export const deleteAccount = 'deleteAccount'
export const driverSelf = 'driver/self'
export const editBank = 'update/payment-account'
export const documentUpdate = 'update/document'
export const updateVehicleRegi = 'update/vehicle'
