export const currency = 'currency'
export const address = 'address'
export const settings = 'settings'
export const language = 'language'
export const plans = 'plan'
export const translate = 'translate/driver-app'
export const taxidoSetting = 'taxido/settings?type=driver'
